id = "yogi-amoled"
name = "Yogi Amoled"
version = "0.1.0"
schema_version = 0
description = "An amoled theme. Based on Monokai Pro theme, but with totally black backgrounds."
repository = "https://github.com/euyogi/Tema-YogiAmoled"
authors = ["Yogi Nam <yogiqhz@gmail.com>"]
themes = ["themes/yogi-amoled.json"]
languages = []

[lib]

[grammars]

[language_servers]
